/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "driverfile.h"
#include <stdio.h>

static void ignit_on(void);
static void led_1(void);
static void led_2(void);
static void led_3(void);
static void ignit_off(void);

int main(void)
{

	init_all_led();				// LED Initialisation
	init_button();				// Butoon Initialiasation

	while (1)
	{
		volatile int flag = button_count();
		if (flag == 1)                        //Activate buttons count according to function
		{	
			ignit_on();
			flag = 0;
		}
		else if (flag == 2)                        //Activate buttons count according to function
		{
			led_1();
			flag = 0;
		}
		else if (flag == 3)
		{
			led_2();
			flag = 0;
		}
		else if (flag == 4)
		{
			led_3();
			flag = 0;
		}
		else if (flag == 5)
		{
			led_1();
			ignit_off();
			flag = 0;
		}
	}
}


static void ignit_on(void)
{
	led_on(LED_RED);
}

static void ignit_off(void)
{
	led_off(LED_RED);
}


static void led_1(void)
{
	led_on(LED_BLUE);
	delay_ms(350);          //1hz -> 350ms
	led_off(LED_BLUE);
	delay_ms(350);
	led_on(LED_GREEN);
	delay_ms(350);
	led_off(LED_GREEN);
	delay_ms(350);
	led_on(LED_ORANGE);
	delay_ms(350);
	led_off(LED_ORANGE);
	delay_ms(350);
}

static void led_2(void)
{
	led_on(LED_BLUE);
	delay_ms(87.5);			//4hz -> 350/4 =87.5
	led_off(LED_BLUE);
	delay_ms(87.5);
	led_on(LED_GREEN);
	delay_ms(87.5);
	led_off(LED_GREEN);
	delay_ms(87.5);
	led_on(LED_ORANGE);
	delay_ms(87.5);
	led_off(LED_ORANGE);
	delay_ms(87.5);
}

static void led_3(void)
{
	led_on(LED_BLUE);
	delay_ms(43.75);			//8hz -> 350/8 =43.75
	led_off(LED_BLUE);
	delay_ms(43.75);
	led_on(LED_GREEN);
	delay_ms(43.75);
	led_off(LED_GREEN);
	delay_ms(43.75);
	led_on(LED_ORANGE);
	delay_ms(43.75);
	led_off(LED_ORANGE);
	delay_ms(43.75);
	}

